### PR TITLE
Review and integrate open199f

### PR DESCRIPTION
**Pull request by charlesh88**
open #199
open #278

Hides Create button when s-status-editing applied;
Adds margin to search-bar input element when
Create button is hidden per above;

### CODE REVIEW

**Comment by akhenry** [comment]
Hrm, create button doesn't seem to work for me, even when I'm not in edit mode?

**Comment by charlesh88** [comment]
Well, that's not good. Can you push to a side branch so I can pull down your exact code base? Or, we could do a Hangout.

**Comment by akhenry** [comment]
I'm testing in open199f?

**Comment by akhenry** [comment]
Haven't merged yet

**Comment by charlesh88** [comment]
Yoiks Shaggy, I just confirmed 199f works fine for me. Can we do a Hangout so I can see your screen?

**Comment by charlesh88** [comment]
Ok, just pushed a fix - the Create menu should now appear properly.

**Comment by akhenry** [comment]
Looks good now, thanks

**Pull request merged**
