### PR TITLE
[Browse] Support default routes other than 'mine'

### PR DESCRIPTION
**Pull request by VWoeltjen**
Move default initial tree selection to a `DEFAULT_PATH` constant, allowing this to be overridden for deployments which do not use "My Items"

https://github.com/nasa/openmctweb/issues/401

### CODE REVIEW

**Comment by VWoeltjen** [comment]
@larkin - is this change sufficient to address #401 or are there cases where an appropriate default selection's ID is not known until run-time?

**Comment by larkin** [comment]
@VWoeltjen selection ids are not known until run time; they depend on the permissions of the currently logged in user.

**Comment by VWoeltjen** [comment]
For that case, my first thought would be to start with the bottom-most object in the tree selected - does that sound like appropriate behavior for this case?

**Comment by larkin** [comment]
yup, I think bottom most or top most is fine.

**Comment by VWoeltjen** [comment]
Bottom-most or top-most&ast; it is then!

### Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? Y
3. Command line build passes? Y
4. Changes have been smoke-tested? Y

&ast; ...only in cases where there is exactly one root-level object

**Comment by larkin** [comment]
@VWoeltjen do you have a tool or process for managing conflicts with the bundle.json -> bundle.js conversion?  Seems to be the main merge conflict here, plus a small conflict with nem changes to browse.

**Comment by VWoeltjen** [comment]
There's a `rebundle` script in the scripts folder, but it relies on having a complete `bundle.json`. Think it will be easier to reconcile by hand since the bundle diff is straightforward.

**Comment by VWoeltjen** [comment]
Resolved merge conflicts, submitting for review again

**Comment by larkin** [comment]
Added a small change in bc6185f to remove the now-unused constant that was moved to the bundle definition.  Otherwise looks good.

# Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Pull request merged**
