### PR TITLE
Open111

### PR DESCRIPTION
**Pull request by akhenry**
Converted developer guide and tutorials to MD. 

- Currently there is no table of contents in either. I would like to add auto-generation of TOC as part of the gendocs.js script, if you think it's a good idea. Alternatively, could be a separate script. My only concern is performance related, requires one pass through the file to find headings (lines starting with #) and then a second pass to find TOC insertion point (though assume this would be at the top of the file). Doubt it will add much to the script's run time though.

### CODE REVIEW

**Comment by larkin** [comment]
I'd say yes, add an automated generation of the TOC.  There's a simple node project that I've used to add a TOC to previous projects:  https://github.com/thlorenz/doctoc

(In general, don't worry about performance-- get something that works, then optimize as necessary).

**Comment by akhenry** [comment]
Author checklist
Changes address original issue? Y
Unit tests included and/or updated with changes? N/A
Command line build passes? Y
Expect to pass code review? Y

**Comment by akhenry** [comment]
Added table of contents generation using doctoc ( https://github.com/thlorenz/doctoc ) - thanks for the suggestion @larkin !

**Comment by VWoeltjen** [comment]
This is looking quite good!

I'm not a fan of adding the TOC in-place, would rather keep things simple. Looks like doctoc only adds TOC's in-place, but I think it would be fairly simple to do TOC generation to the markdown processing pipeline in gendocs using something like https://github.com/jonschlinkert/markdown-toc

Alternately, you could just pull out the TOC generation (and generated TOCs) and file a follow-up issue for that feature of the documentation

**Comment by akhenry** [comment]
My original plan for TOC was to do something bespoke as an additional step in the MD generation pipeline. Luckily Pete saved me the trouble by pointing me to an existing solution :) I agree though that, keeping it all in one place makes sense. It might be a little awkward fitting it around the existing pipeline though, because from memory the pipeline processing via transforms works on chunks? TOC generation requires one full pass through the entire document to find all of the headings, and then a second pass to find the TOC insertion point.

**Comment by larkin** [comment]
It isn't desirable to have generated markup be added to the source files, but the build process isn't very simple to adapt either.

In my opinion, having a table of contents in our documentation is more valuable than having perfectly clean source code and would vote to open a follow-up ticket for cleaner TOC handling.

**Comment by VWoeltjen** [comment]
My assumption was that this would be a pretty simple change to `gendocs.js` - filed pull request #200 for this. It's a smaller changeset to doc generation, so I think this PR could be simplified to omit TOC handling entirely.

**Comment by larkin** [comment]
A+.  Toss back to andrew to pull out TOCs?

**Comment by VWoeltjen** [comment]
Thanks for the reminder - reassigned to roll back the TOC changes on this issue. Looking forward to having these docs in the repo!

**Comment by akhenry** [comment]
TOCs removed. I'll take a look at doing the generation as part of the pipeline.

**Comment by VWoeltjen** [comment]
I've filed #200 for TOC generation as part of the pipeline, so no need to worry about that here. Turned out to be fairly simple after finding a library that made it simple.

**Comment by VWoeltjen** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/A (changes to documentation only)
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Pull request merged**
