### PR TITLE
[Plots] #638 New plot display options

### PR DESCRIPTION
**Pull request by akhenry**
Early PR for visibility and comments.

## Ch-ch-ch-ch-changes ★

1. Have defined a new attribute of Types called "regions". Regions are sections of the browse and edit screens for an object that, while fixed in location, have content that is completely customizable on a per-type basis. Regions are represented in code by a new [Region](https://github.com/nasa/openmctweb/compare/open638?expand=1#diff-39d7cd40d9d7626dedcec0e25741e5b3R57) class. Within `Region`s are `RegionPart`s. A `Region` can have any number of `RegionPart`s defined. The layout of both Regions and RegionParts are defined by representations. Whether a region part is visible within a region can depend on object state, and is determined by a policy of category `region`. 

2. Defined a new TypeRegionDecorator that defines standard regions for objects to avoid having to add region sections to all type definitions. Only have to explicitly define regions if a type has special requirements, such as the new plot display options.

3. Defined a new [EditableRegionPolicy](https://github.com/nasa/openmctweb/compare/open638?expand=1#diff-541e7a25773dc982afaf5628b89c9e6bR37) which provides a convenience method for determining whether a region part should be visible in edit/browse mode based on a [modes](https://github.com/nasa/openmctweb/compare/open638?expand=1#diff-4099ffc24d3df74cb55a5eabf32a36bfR51) attribute in `RegionPart` definition.

4. Modified the browse and edit screens to define an Inspector region.  Currently this is the only region defined, however I will also defined 'object view' and 'elements' regions. Within the object inspector is the standard properties and location sections.

5. Added a very basic mct-form definition to the plot options region part. __mct-form needs some modification to support plot options - see below__

### General
* Define a new type for plots. __Currently the plot options region part is defined for panels because there is no plot object type__
* Integrate with @larkin's plot changes. In particular, how to communicate changes in plot view options to the plot itself. My thinking is that because plot view options will be persisted as configuration on the options, the plot can just listen to mutation events on the object and reload the config. We need to coordinate on this though.
* The RegionController is a little clunky at the moment. At the very least it needs a more performant approach to filtering region parts.
* Define regions for object view and elements
* Incorporate regions into NEM refactoring as it allows for separation of markup for browse and edit mode versions of a screen.

### Modifications needed in mct-form
* Support re-ordering of labels and controls (currently labels are always to the left of controls, this is incompatible with the screen mockups)
* Support the addition of a glyph / icon in between control and label. @charlesh88 - where are these images going to come from?
* Style changes necessary to make forms look nice in the inspector sidebar. @charlesh88 Are you working on markup / style changes for this at the moment? If not I could use some help with this.
* Currently overflow is messy in the sidebar with the elements section and doesn't work. @charlesh88 might need some help with this also.

### CODE REVIEW

**Comment by charlesh88** [comment]
@akhenry I am looking at #638 now. Very exciting! I'll do work in something like open638a, then file a PR to get it back into open638 unless you'd like otherwise.

**Comment by larkin** [comment]
I think observing object for changes is a fine way to communicate via widgets initially.  Let's see how that gets there.

**Comment by larkin** [comment]
@akhenry I've drafted a rough starting point for plot configuration object.  I think we could have a bunch of different ways of describing configuration for interpolation and line style that requires our forms to have some specialized logic-- some options are not relevant if others are checked, etc.  

```javascript
{
    yAxis: {
        // A multi-y-axis plot would have this defined per plot series.
        autoscale: true, // if true, min/max are ignored.
        min: 0,
        max: 15,
        range: 'eu' // or 'dn' or 'status'. 
    },
    xAxis: {
        // could potentially have options for time following behavior, but that's out of scope right now.
        domain: 'scet' // or 'sclk' or 'lst' or 'sclk'-- ideally dynamic options list, not required.
    },
    plotSeries: [
        {
            telemetryId: "de123d54-75b4-431b-adb2-eb6b9e546014",
            lineStyle: "markers",
            color: "#aaddaa", // or undefined for "auto"
            interpolation: "none" // or "linear" "step-after" or whatever 
        },
        {
            telemetryId: "abcd5d54-75b4-431b-adb2-eb6b9e546014",
            lineStyle: "markers",
            color: "#aaddaa", // or undefined for "auto"
            interpolation: "none" // or "linear" "step-after" or whatever 
        }
    ]
    // not exposed by form; would be analagous to elements panel
    // telemetry sources for each plotSeries must be contained here:
    composition: [
      "de123d54-75b4-431b-adb2-eb6b9e546014",
      "abcd5d54-75b4-431b-adb2-eb6b9e546014"
    ]
}
```

your thoughts?

**Comment by VWoeltjen** [comment]
Would recommend same JSON structure for both axes, e.g. key instead of domain/range. UX treats both axes differently but don't want to leak that into data model. 
________________________________________

**Comment by akhenry** [comment]
A couple of questions

* The values for domain and range, presumably we want a select box for this. Where will the options come from? Will `eu`, `dn`, etc be predefined somewhere, or will they be telemetry point specific? Are they values that should be defined in OMW or are they application-specific? 
* Color: Would be great to have a selector for this. @charlesh88 thoughts?
* What are the options for `Linestyle`? Is this a select?
* Which of these configuration options corresponds to the options shown in the UI spec? Interpolation? Linestyle?

**Comment by larkin** [comment]
@akhenry we have a color control already from fixed panel drawing, might need some tweaking for flexibility.  As a data storage target, raw data values would be hex color code or undefined.  If users can pick colors from a list, need to be able to configure that list as some options are not valid in all instances (for example, transparent).

Regarding eu/dn: they are dynamic, and while initially hard coded works, we should allow them to be dynamic.  This is why I find our current form schema a bit lacking-- I would prefer a "code over configuration" focus that allows for more flexibility.

*linestyle* and *interpolation*: this is just a random term to represent where one of the radio options in the current designs would live.  I imagine you can represent this how you'd like.  Radio fields and select fields are very similar inputs that allow a user to choose from a list; their options should be very similar.  I imagine the plot controller will translate these options to more fine grained controls that have more meaning in the drawing library instead of implementing exactly what they say.

@charlesh88 While we're working on design can we put in space for additional plot options and requests to ensure we're keeping our design space wide when we look at forms and other needs?  Will help us ensure we're thinking about the right things from the data model standpoint.

Some thoughts:
* Form drop down for picking range (eu/dn/status) and domain (scet/sclk/etc). (consider how this would play with multiple y-axis)
* autoscaling y-axes versus user defined min/max (also consider interactions with multi y-axis)
* user configurable line color

**Comment by VWoeltjen** [comment]
One more not on JSON for plot configuration - thus far, view configurations have been stored in the model as `configuration.<view key>`, e.g.:

```json
{
    "composition": [ "a", "b" ],
    "configuration": {
        "plot": {
            "xAxis": { },
            "etc"
        }
    }
}
```

This is compatible with both the view-of-object and view-as-object approaches, so I'd prefer to stick with it. Note that EditRepresenter should be making `model.configuration.plot` available in the view's scope as `configuration` (unless that has been changed for NEM)

> Modifications needed in mct-form

Changes seem non-functional (but haven't seen the UI screens); could we defer this to a followup issue to reduce scope, or would there be UX impact?

**Comment by larkin** [comment]
`configuration.<view key>` seems a fine standard to keep, though it's something I have never actually known before this moment.  Same with `configuration` being exposed by representer--  Implementation wise, would love a more direct path to the data so it's easier to follow and understand what is being referenced.

**Comment by VWoeltjen** [comment]
> `configuration.<view key>` seems a fine standard to keep, though it's something I have never actually known before this moment. Same with `configuration` being exposed by representer-- Implementation wise, would love a more direct path to the data so it's easier to follow and understand what is being referenced.

It is minimally [documented](http://nasa.github.io/openmctweb/guide/#view-configurations), but yes, very easy to miss. There really does need to be some object with a clear interface (as opposed to "variables passed via scope") for dealing with these; added a note to consider this in the context of UI components in #463.

**Comment by akhenry** [comment]
@VWoeltjen The only ones that are essential are
> Style changes necessary to make forms look nice in the inspector sidebar. @charlesh88 Are you working on markup / style changes for this at the moment? If not I could use some help with this.
> Currently overflow is messy in the sidebar with the elements section and doesn't work. @charlesh88 might need some help with this also.

The others can be deferred, but I believe @charlesh88 has made a start on them and has probably made significant progress by now.

**Comment by akhenry** [comment]
> @akhenry we have a color control already from fixed panel drawing, might need some tweaking for flexibility.  As a data storage target, raw data values would be hex color code or undefined.  If users can pick colors from a list, need to be able to configure that list as some options are not valid in all instances (for example, transparent).

@charlesh88 can we integrate this with mct-form and make it a standard control?

> *linestyle* and *interpolation*: this is just a random term to represent where one of the radio options in the current designs would live.  I imagine you can represent this how you'd like.  Radio fields and select fields are very similar inputs that allow a user to choose from a list; their options should be very similar.  I imagine the plot controller will translate these options to more fine grained controls that have more meaning in the drawing library instead of implementing exactly what they say.

Was more interested in the possible values there and with reconciling with the UI design, but we can finesse that later. Radio vs select is not super important. Perhaps select though initially just because it requires less screen real estate.

**Comment by akhenry** [comment]
@larkin Is the intention to perform domain and range selection from the inspector? Would this replace or augment the axis selection on the plot itself?

**Comment by larkin** [comment]
@akhenry augment.  And also support multi-y axis, which as an interaction, doesn't seem to evolve out of the current dropdown-by-clicking-axis.

**Comment by charlesh88** [comment]
Domain and range selection in the Inspector should ideally augment selection in the plot itself. If we're tackling multi-Y axis, I absolutely want to weigh in the design first before we begin any dev on this.

**Comment by larkin** [comment]
Right-- this isn't tackling multi-axis directly.  it's primary goal is augmenting selection in the plot itself.  

The general idea being: anything we expose via the plot view should be trivial to include in the inspector.

**Comment by akhenry** [comment]
@larkin how do you want to approach the merge here? If we merge into one branch and do a single PR it's going to be a lot of code to review

Makes sense to split them

1. I can merge my changes into master without the plot options being enabled for any object types.
2. You could do the same with your plot changes.
3. I could then create a branch that merges our two and adds in the wiring, and create a separate PR for it?

Alternatively I could do 1. then do a second PR that merges my changes with yours. Then I create a PR that would have the effect of merging in your branch + any wiring between our code.

Thoughts?

**Comment by larkin** [comment]
@akhenry that is how we should do it-- you merge to master, I merge to master, we do a third branch to wire the two together.

**Comment by akhenry** [comment]
@larkin sounds good.

> plotSeries: [
        {
            telemetryId: "de123d54-75b4-431b-adb2-eb6b9e546014",
            lineStyle: "markers",
            color: "#aaddaa", // or undefined for "auto"
            interpolation: "none" // or "linear" "step-after" or whatever 
        },
        {
            telemetryId: "abcd5d54-75b4-431b-adb2-eb6b9e546014",
            lineStyle: "markers",
            color: "#aaddaa", // or undefined for "auto"
            interpolation: "none" // or "linear" "step-after" or whatever 
        }
    ] 

I have deviated slightly here and made plotSeries an associative array, eg.
```
plotSeries: {
    "de123d54-75b4-431b-adb2-eb6b9e546014": {
        lineStyle: "markers",
        color: "#aaddaa", // or undefined for "auto"
        interpolation: "none" // or "linear" "step-after" or whatever 
    },
    "abcd5d54-75b4-431b-adb2-eb6b9e546014": {
        lineStyle: "markers",
        color: "#aaddaa", // or undefined for "auto"
        interpolation: "none" // or "linear" "step-after" or whatever 
    }
} 
```
Will that work for you?

**Comment by larkin** [comment]
@akhenry associative array is not great, there is a possibility that the same telemetry object could be added twice. Not currently, but we have had that problem with other view types and that's why I think it's better not to do associative.

**Comment by akhenry** [comment]
Ok, np, I'll go with an array.

**Comment by akhenry** [comment]
@charlesh88 I have pushed the (almost) final version of this. I had to hack in a little more styling for the forms. It's all contained within [plot-options-browse.html](https://github.com/nasa/openmctweb/pull/645/files#diff-0cf515d9304eeaf0ab406573ed5df82dR22). Would you mind taking a look at this de-crapifying it?

Also, when I try and merge with master I get conflicts on the icon files. Would you mind terribly resolving the merge conflict here?

@VWoeltjen @larkin Aside from the style issues, we're ready to go with this PR. Have at it.

@larkin I have left the series configuration as an associative array for now. In wiring it up with yours I will switch to an indexed array. It's going to take a little work to support it properly and I didn't want to hold up this PR any longer.

**Comment by akhenry** [comment]
I take that back, it's not ready yet, I need to disable for panels, one sec...

**Comment by akhenry** [comment]
Ok, the code is all in there now, but the plot options field is effectively disabled because it's not being added to any object types at the moment. For testing purposes I was adding it to panels. An example of how region registration works for a type can be seen in the history for [layout/bundle.js(https://github.com/nasa/openmctweb/commit/ea8d0ec055113c4620f33dd99e9a7dac69]53d7f7#diff-4099ffc24d3df74cb55a5eabf32a36bfR47)

**Comment by larkin** [comment]
@akhenry can you add an example bundle which exposes a type with these configuration options?

Also, if you rebase on master that should clear up the conflicts.  If that rebase ends up with a conflict, abort it, do an interactive rebase, and drop any commits that were cherry-picked into this branch, and you'll have no conflicts.  The ui symbol changes will be merged into master in #644.

**Comment by akhenry** [comment]
@larkin yeah fair enough, I'll add an example bundle with a new type that enables the plot options.

**Comment by akhenry** [comment]
@larkin don't believe there are any cherry-picked commits in this. I'll try rebasing onto master and see how it goes.

**Comment by larkin** [comment]
@akhenry https://github.com/nasa/openmctweb/commit/d968c0f658c6308a411b1a665d0678d768ddcf4c https://github.com/nasa/openmctweb/commit/61fc041ffa6c0221509bbc14633ed1bec5bee995 https://github.com/nasa/openmctweb/commit/11b121ce64f63d3baa891632f15d0a5297aff61f

**Comment by akhenry** [comment]
Closing this temporary PR. Have created a new PR for the final merge at #651

**Comment by larkin** [comment]
@akhenry any reason to close an existing pr and open a new one for the same code?  this splits up the discussion and makes it harder to track the history of the feature.

**Comment by akhenry** [comment]
Rebase was done in another branch, wanted to preserve the pre-rebase branch as well. I realize that there are ways around this that would have allowed continuing this PR, but I also thought that it made sense to separate the comments on the implementation as it was eventually realized distinct from the more preliminary discussions as I expect that there will be quite a bit of discussion on implementation details.

**Comment by larkin** [comment]
@akhenry hear ya, can force push rebase over original branch.  In general, I am on the side of keeping history all in one place.  We already have three repositories and at least 500 open issues; anything we can do to reduce the number of links we have to traverse is ideal.

Not to mention it's pretty common:
screen shot 2016-02-04 at 5 33 05 pm
(from http://zachholman.com/talk/how-github-uses-github-to-build-github/:)

**Pull request closed without merging**
