### PR TITLE
Mobile

### PR DESCRIPTION
**Pull request by shivamndave**
Pull request for demo deployment.

### CODE REVIEW

**Comment by charlesh88** [comment]
Shivam,
Your stuff is beautiful! Great work. Thanks for getting the arrow click of a tree item to dismiss the tree and go to the object. We need to do the same thing when a user clicks a leaf node in the tree as well.

**Comment by VWoeltjen** [comment]
Assigning to self; would like to complete the merge this sprint. Need to review, but looks like this might just need a checklist and a merge.

Once this is done, should go through and close mobile issues that are resolved

**Comment by VWoeltjen** [comment]
It is desirable to have this merged in time for testathon 9/17/2015

**Comment by VWoeltjen** [comment]
We especially want this merged & tested by 10/13/2015. We believe that the world won't end if this doesn't happen, but do we really want to take that chance?

**Comment by larkin** [comment]
Ah I'd put a note on my list to look at this but it looks like you're on this already @VWoeltjen.  It looks like the scope of these changes don't include plot gestures which is good-- I don't think the new plots are ready for a testathon.  Should be reasonable to get merged by next week's testathon.

**Comment by VWoeltjen** [comment]
Reviewed changes, looking pretty solid! Things I want to address before marking this as ready-to-merge:

- [ ] Add a `platform/commonUI/mobile` bundle to separate out as much of the mobile-specific behavior as possible
- [ ] `back-arrow` should have its own controller instead of reusing BrowseController
- [ ] Solicit review of HTML changes from @charlesh88 
- [ ] Separate out additions to `BrowseController` where it makes sense
- [ ] Remove leading slashes from `agentService`, `urlService` implementation properties (for consistency)
- [ ] Change `agentService` such that `navigator.userAgent` doesn't need to be passed in (I can't imagine any cases where we'd want to pass anything else in there)
- [ ] Change `agentService.getOrientation()` to `agentService.isPortrait()` and `agentService.isLandscape()`, and similarly remove the need to pass in dimensions (instead, `agentService` can depend on `$window` and work it out that way)
- [ ] Remove `setObject` from `TreeNodeController`; I think whatever is listening to this event could just listen to the `navigationService` directly and dismiss the tree when navigation changes
- [ ] Ensure test coverage for all added/modified classes

I'm also not a fan of how much iffing is happening in the gestures, but I think the problem is architectural, since `gestures` currently relate DOM interactions directly to actions. Introducing an intermediary would allow this logic to be separated out from the detection of DOM interactions - filed #110 for this.

**Comment by VWoeltjen** [comment]
Done making the changes listed above. Reassigning to @larkin because the changes I've made are extensive enough to warrant review from another party.

### Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? Y
3. Command line build passes? Y
4. Expect to pass code review? Y

@charlesh88 - can you look over the HTML changes and give a thumbs-up/thumbs-down?

**Comment by charlesh88** [comment]
Will checkout the HTML changes per request.

**Comment by charlesh88** [comment]
Just had a look at markup changes, all looks good. I created a temp branch based on open95b, updated it with the latest master, then merged in mobile. The only markup files that are different from open95b are:
- platform/commonUI/browse/res/templates/browse.html
- platform/commonUI/general/res/templates/tree-node.html
No CSS was modified in a way that is causing any problems. The only issue I see is that navigating to an object via the tree while in phone portrait mode should cause the tree to be hidden. I thought Shivam had fixed this later in his dev effort, but I'm not 100% certain.

**Comment by VWoeltjen** [comment]
Diagnosed the issue with navigating via tree & hiding tree when this occurs; will push additional changes to this branch as a consequence, hold off on merge until then

**Comment by VWoeltjen** [comment]
Adding changes referenced above, feel this is ready to merge now.

**Comment by larkin** [comment]
Made some tweaks to test specs, primarily removing unused code.  Small enough changes that I will merge w/o a second review.

# Review Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Project-specific information isolated to appropriate branches? Y

# Integration Checklist

1. Automated build passing after merge? Y
2. No merge conflicts (or resolution trivial/obvious)? Y
3. All master branches up-to-date after merge? Y
4. Project-specific information isolated to appropriate branches? Y

**Pull request merged**
