### PR TITLE
[Inspector] Introduce inspector pane

### PR DESCRIPTION
**Pull request by VWoeltjen**
Recreates PR #233 with changes merged from master.

### CODE REVIEW

**Comment by VWoeltjen** [comment]
@charlesh88 - this is the same content as `open90`, using a merge commit so that git can reconcile this against master. Can you look through the diff and verify that these changes appear correct/complete?

@larkin - as a bonus, dataset glyph is in among these changes

**Comment by VWoeltjen** [comment]
@charlesh88 - I see that Inspector is here (looks fantastic btw!), but don't see a way to collapse the tree view (on my laptop) using this, which I'd expected based on wording of #90.

**Comment by VWoeltjen** [comment]
See #233 for author checklist.

Made changes (1c4a4e475be57f7cbaef25f0f6819f1e3854ce30) based on review; considering these changes trivial and proceeding to merge.


### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Comment by charlesh88** [comment]
Thanks! You don't see a close "X" in the upper right of the treeview, to the right of the Create button? And, if it is there, did you not notice it? That would be good usability input.
screen shot 2015-11-04 at 10 56 05 am

**Comment by VWoeltjen** [comment]
Nope, not seeing the X locally. I'm wondering if this is the same root cause as #169 - CSS rules detect my laptop as a tablet. (My laptop is pretty tiny!)

**Comment by VWoeltjen** [comment]
missingx

Attached is a screenshot of what I see locally.

**Comment by VWoeltjen** [comment]
Verified that this is indeed triggered by my little screen size; as a test, found-replaced `min-device-height: 800` with `min-device-height: 600` locally in theme-espresso.css and those little X's show up and behave as expected.

I'll amend the description of #169 to include this, don't think we need to solve this here. Completing merge.

**Comment by charlesh88** [comment]
@VWoeltjen I think this might be a "loophole" in Shivam's media queries. For example, the lowercase "i" Info icon is displaying on your items in the grid - that's mobile-only. Real mobile though should convert the "X" for the tree pane to the hamburger. I think what might be happening is some elements are failing to meet both the desktop media query *and* the tablet/phone query, so they don't display.

Could you reply with your screen dimensions?

**Comment by charlesh88** [comment]
Woo hoo on the integration - thanks!

**Comment by VWoeltjen** [comment]
Screen is 1366x768

**Pull request merged**
