### PR TITLE
[Info Bubble] Add info bubble

### PR DESCRIPTION
**Pull request by VWoeltjen**
Add info bubble to domain objects in the tree and in the items view of a folder.

Summary of changes:
* Add a "bubble" container to display other templates inside of bubbles
* Add an "info-table" container to display tabular metadata
* Add an `infoService` to programmatically show an info bubble at specific locations.
* Add an `info` gesture to show info bubbles over domain object representations on hover.
* Add a `metadata` capability to provide information that should appear in info bubbles. 

Also noticed that test coverage for DateTimeController was low while preparing unit tests for this; added an extra test case there to bring coverage back to 100%.

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? Y
3. Command line build passes? Y
4. Expect to pass code review? Y
5. Project-specific information isolated to appropriate branches? Y

### CODE REVIEW

**Comment by charlesh88** [comment]
Review Checklist
- Changes appear to address issue? Y
- Appropriate unit tests included? Y
- Code style and in-line documentation are appropriate? Y
- Commit messages meet standards? Y
- Project-specific information isolated to appropriate branches? Y

**Comment by charlesh88** [comment]
There are going to be merge conflicts going into open-master. Suggest I merge open-master into open884 and push the clean result back up. We may want to just rope in the bug fixes from open1248 (that covers bugs WTD-1247 and WTD-1248) and do this all at once. Let's discuss.

**Comment by VWoeltjen** [comment]
Yep, think this approach makes sense. Agree that we can go ahead and bring in open1248 as well

Think sequence of merges looks like:
- Checkout open884
- Merge in open-master
- Merge in open1248
- Push open884

**Comment by charlesh88** [comment]
I will make it so.

**Comment by charlesh88** [comment]
open884 has had open-master and open1248 merged into it, with all conflicts resolved. It has been pushed back to origin.

**Comment by VWoeltjen** [comment]
Integration Checklist

Automated build passing after merge? Y
No merge conflicts (or resolution trivial/obvious)? Y
All master branches up-to-date after merge? Y
Project-specific information isolated to appropriate branches? Y

**Pull request merged**
