### PR TITLE
[Persistence] Errors in persistence (after creating/modifying objects) should be visible to user #58

### PR DESCRIPTION
**Pull request by akhenry**
As per https://github.com/nasa/openmctweb/issues/58#issuecomment-161200080 I've pushed the notification version of it for now. Discussion needed on whether we should go with this temporary solution, or instead a blocking dialog with temporary disablement or complete removal of PersistenceFailureHandler.

### CODE REVIEW

**Comment by VWoeltjen** [comment]
Changes look good - think this is ready to merge. A couple of notes:

1. Needs Author Checklist
2. `notificationService` is called `alertService` from the persistence capability. Is there a reason for this? All else being equal, think we should be consistent.
3. Don't think we need to address this now, but it feels a little funny to me that we're using `notificationService` from a core capability. Think we could reduce coupling by using decoration or eventing or similar. Again, not a concern for this issue, but want to look at ways to reduce the impedance of using these strategies in the context of API redesign.

Only changes I see needed are trivial (Author Checklist, find-replace on `alertService` unless there's some reason for the rename); reassigning back to @akhenry to follow up on these and complete the merge.

### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Comment by akhenry** [comment]
notificationService is called alertService from the persistence capability. Is there a reason for this? All else being equal, think we should be consistent.

Yeah, agreed. The reason for calling it alertService was an attempt to decouple it from the actual service used (notification vs. dialog) based on the ongoing discussion. It doesn't really work very well because the APIs are fundamentally different (although I attempt to reconcile them in #361 .

I'll rename the variables to notificationService, it's easy enough to refactor this later if/when we switch to a blocking message.

**Comment by akhenry** [comment]
Don't think we need to address this now, but it feels a little funny to me that we're using notificationService from a core capability. Think we could reduce coupling by using decoration or eventing or similar. Again, not a concern for this issue, but want to look at ways to reduce the impedance of using these strategies in the context of API redesign.

Again, totally agree. Based on the discussions in #58 this is a temporary measure, and it will be removed down the line. Failure notifications should probably happen higher in the stack (although there are pros and cons of this approach, a major con being consistency of UX if we leave it to actions etc. to indicate to the user that there's been an error). 

Re: "decoration or eventing or similar" - yeah tbh this is an area of the API that I'm still a little murky about. I'm not clear on what the API offers in this respect, and need to spend some more time in the dev guide :)

**Comment by akhenry** [comment]
### Author Checklist

1. Changes address original issue? __Y__
2. Unit tests included and/or updated with changes? __Y__
3. Command line build passes? __Y__
4. Expect to pass code review? __Y__

**Pull request merged**
