### PR TITLE
[Tree] Rewrite tree without Angular

### PR DESCRIPTION
**Pull request by VWoeltjen**
...instead, use Zepto to handle DOM manipulations more directly in response to user actions and mutation events. Goal is to reduce the watch count associated with the tree, #732 and #315. Also serves as informative prototyping for interfaces for non-Angular UI components, #463.

Still needed for parity/completion:

- [x] Click to select nodes
- [x] Highlight selected nodes
- [x] Expand to show nodes on selection change
- [x] Allow drag
- [x] Allow context menu
- [x] Show info bubble
- [x] Wait spinner
- [ ] Refactor out commonalities of Views
- [x] Tests
- [ ] JSDoc

### CODE REVIEW

**Comment by VWoeltjen** [comment]
Test case:

* Enable `example/taxonomy` and `example/profiling`
* Expand all three "subsystems" in the example taxonomy, select "Stub Subsystems"

Watch counts:

master | tree-732
:---:|:---:
12616 | 469

:smiley:

**Comment by larkin** [comment]
That's a serious happyface for watch reduction.

Very interesting to look at this as a prototype for how to add custom views with very minimal angular usage: the binding around the directive is pretty simple.

Are you looking to merge this for testing tomorrow?

**Comment by VWoeltjen** [comment]
> Are you looking to merge this for testing tomorrow?

Yep. There are still a few to-dos listed above. My thinking is to add sufficient tests here (to support refactoring) and defer the actual refactor to a subsequent issue. Also think it would be useful to defer JSDoc until a refactor; there are a lot of commonalities that could be pulled up to parent classes, and docs will be a lot simpler once that has occurred.

I did find the Angular wrapping to be remarkably simple (and easy to insulate from everything else.) That said, I also used the Angular wrapping as a starting point, so that simplicity was a bit forced. Do think this is interesting as a prototype for future non-Angular components.

**Comment by VWoeltjen** [comment]
In the interest of getting this in for tomorrow's testathon, would like to review in its current state and defer to another issue:

* Refactoring out commonalities
* More complete/focused testing
* JSDoc (as refactoring will change this)

### Author Checklist

1. Changes address original issue? Y &ast;
2. Unit tests included and/or updated with changes? Y &dagger;
3. Command line build passes? Y
4. Changes have been smoke-tested? Y

&ast; #315 is completely addressed; #732 is a broader performance issue and may not be completely addressed, but one heavily-suspected cause of failure to GC is addressed (reduction of watch count associated with tree)
&dagger; Unit tests meet coverage requirements, but are not very focused - only outermost tree view class is tested. Would like to defer testing of inner components until after refactoring.

**Comment by larkin** [comment]
@VWoeltjen I'm okay with skipping proper testing as we know this is due to be refactored.  Also, the performance gains are significant and it's clear that GC's are running properly now.  I have tested in VISTA environment as well and performance improvements are significant.

# Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Pull request merged**
