### PR TITLE
[Entanglement] Allow cross-space linking

### PR DESCRIPTION
**Pull request by VWoeltjen**
Allow links across spaces; only disallow move or copy.
Addresses WTD-1587

### CODE REVIEW

**Comment by VWoeltjen** [comment]
@larkin - this addresses an issue in WARP where Packets can no longer be placed in Layouts (or Telemetry Points into Panels, for that matter). Dictionary hierarchy uses the same prefix convention that is used for persistence spaces. Could change convention in WARP, but conceptually these are objects from a different space (that also happen to be non-writable) so think interpreting these identifiers in this manner is reasonable. Impact in VISTA is that links could be created across spaces; think this is okay (either you have permissions to read the space and you see the linked object, or you don't have permissions and you see a Missing object.)

### Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? Y
3. Command line build passes? Y
4. Expect to pass code review? Y

**Comment by larkin** [comment]
@VWoeltjen I assume that this would resolve the same issue in vista with vista telemetry points provided by dictionaries (they use the same idea of a persistence space prefix).  I agree that cross-space linking is safe though in some cases may be undesirable; can prevent that later with additional (perhaps deployment specific) policy.

**Comment by VWoeltjen** [comment]
> I assume that this would resolve the same issue in vista with vista telemetry points provided by dictionaries (they use the same idea of a persistence space prefix).

Yes, I would expect this to be resolved as well (sounds very much like same root cause)

**Comment by larkin** [comment]
I haven't actually demonstrated the bug in VISTA but I imagine it would be there.

**Comment by larkin** [comment]
# Review Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Project-specific information isolated to appropriate branches? Y

# Integration Checklist

1. Automated build passing after merge? Y
2. No merge conflicts (or resolution trivial/obvious)? Y
3. All master branches up-to-date after merge? Y
4. Project-specific information isolated to appropriate branches? Y

**Pull request merged**
