### PR TITLE
[bug] TypeImpl.getInitialmodel should always return a fresh (ie. cloned) model.

### PR DESCRIPTION
**Pull request by akhenry**
See #316

### CODE REVIEW

**Comment by VWoeltjen** [comment]
Changes look good to me. Curious if there will be a performance impact, but don't see any immediate cause for concern; `getInitialModel()` is only used by the `create` action and by composition policy, and in the latter case only at initialization time.

Attaching Reviewer Checklist and reassigning over to @akhenry to complete the merge once an Author Checklist is also attached.

### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Comment by akhenry** [comment]
Yeah, totally understand your concern. I think it's more important in this case that the default model for a type doesn't inadvertently get tainted as it did in this case. I don't think the method is heavily utilized, but I will add a performance note to the jsdoc on that method to encourage caching the result if it's going to be used heavily, like in a loop or something.

**Comment by akhenry** [comment]
### Author Checklist

Changes address original issue? __Y__
Unit tests included and/or updated with changes? __Y__
Command line build passes? __Y__
Expect to pass code review? __Y__

**Comment by VWoeltjen** [comment]
:+1: Like the note, clearly conveys both the costs and behavior of the method so user code can be implemented accordingly.

**Pull request merged**
