### PR TITLE
[Code Style] Refactor platform to use prototypes

### PR DESCRIPTION
**Pull request by VWoeltjen**
Refactor JavaScript sources in the platform to use prototypes for classes, instead of the "revealing module" pattern.

Summary of changes:
- Move methods from anonymous objects to the `prototype` of the constructor function defined in each script.
- Clean up associated JSDoc, including adding definitions for several interfaces.
  - Using `@namespace` to identify bundles, since it has the cleanest syntax for usage, and is not in use for other purposes.
- Renamed some scripts (specifically, DomainObject -> DomainObjectImpl, so that DomainObject can be documented as an interface.)
- Removed example code from JSDoc-generated docs
- Added a contributing guide to formalize changes to code style.

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? Y <sup>1</sup>
3. Command line build passes? Y
4. Expect to pass code review? Y
5. Project-specific information isolated to appropriate branches? Y

<sup>1</sup> Some unit tests updated, but since this was a refactor most unit tests remain unchanged.

### CODE REVIEW

**Comment by larkin** [comment]
@VWoeltjen CircleCI hits 7 failures when running tests with Karma.  I believe it's because maven runs tests based on bundles.json, where as Karma runs every spec regardless of currently specified bundles.

I will push a fix for these tests.

**Comment by VWoeltjen** [comment]
Pushed fixes for failing tests, verified locally with `npm run test`

**Comment by larkin** [comment]
Reviewer Checklist

* Changes appear to address issue? Y
* Appropriate unit tests included? Y
* Code style and in-line documentation are appropriate? Y
* Commit messages meet standards? Y

**Comment by larkin** [comment]
Integration Checklist

* Automated build passing after merge? Y
* No merge conflicts (or resolution trivial/obvious)? Y
* All master branches up-to-date after merge? Y
* Project-specific information isolated to appropriate branches? Y

**Pull request merged**
