### PR TITLE
Review and integrate open90: Expand/collapse Treeview and Inspection

### PR DESCRIPTION
**Pull request by charlesh88**
This branch ended up manually integrating (rather than merging) work from open73 (#73) by Shivam Dave and Sarah Hale, due to severe merge issues and incomplete development. Some notes:
- Most of the manual integration was focused on integrating the expand/collapse functionality with similar but duplicate functionality earlier integrated via mobile. open90 provides a consolidated approach that works properly in desktop and mobile.
- Sarah's work on the core of Inspection (/platform/commonUI/general/src/controllers/ObjectInspectorController.js and its spec.js) was brought over as was.
- A change to the splitter's approach to margins and the look of split panes necessitated significant changes to markup in /platform/commonUI/.../browse.html and MCTSplitPane.js. The splitter no longer adds spacing around the splitter element; rather, the splitter via CSS now creates its margins via its width. This allows themes to have splitters that look and feel different, while decoupling the splitter JS code from look-and-feel.

**Author checklist:**
- Changes address original issue? Y
- Unit tests included and/or updated with changes? Y
- Command line build passes? Y
- Expect to pass code review? Y

### CODE REVIEW

**Comment by charlesh88** [comment]
Fixing ci errors...

**Comment by charlesh88** [comment]
Woo hoo! Fixed problems. Reassigning back to Victor.

**Comment by charlesh88** [comment]
Crap, lots of conflicts with master now that messages are in. Fixing...

**Comment by charlesh88** [comment]
Fixed merge issues with master and pushed up. Prior version of open90 backed up as open90-premerge-master.

**Comment by charlesh88** [comment]
@VWoeltjen Can we please review and integrate this before more changes are pushed to master? :)

**Comment by larkin** [comment]
@charlesh88 Hrm, this is still showing conflicts with master, seems something must be off here.  We also ran into some conflicts related to custom fonts-- seems that not all commits are getting merged to master and as a result conflicts are appearing.

Can look into it more in the morning.

**Comment by VWoeltjen** [comment]
Looking at this now - this is another case where I see a commit (63798ff756c85fb0c9efb8320a02c2aace30d127) labelled a merge in commit messages, but with only a single parent.

I'll see if I can resolve this using the pre-merge branch.

**Comment by VWoeltjen** [comment]
Closing; relevant changes have been merged with #240

**Pull request closed without merging**
