### PR TITLE
[New Edit Mode] Adding sub objects to Timelines

### PR DESCRIPTION
**Pull request by akhenry**
Addresses #480 and enables adding of activities to timelines in edit mode. 

Summary of changes:
1. Added a new AddAction and test specs for adding sub objects to an edited object.
2. Resolved a [problem](https://github.com/nasa/openmctweb/issues/305#issuecomment-163792108) identified in EditableDomainObject that meant DomainObject functions were not being wrapped by EditableDomainObject
3. Added new `EditableInstantiationCapability` so that objects created via the Instantiation capability of an EditableDomainObject are themselves EditableDomainObjects without needing explicit wrapping.
4. Moved some wizard-specific code shared between AddAction and SaveAction out of SaveAction and into the CreateWizard itself.
5. Modified CreateWizard to make locator optional. Locator is no longer visible for add sub-objects

### CODE REVIEW

**Comment by akhenry** [comment]
## Author Checklist

1. Changes address original issue? __Y__
2. Unit tests included and/or updated with changes? __Y__
3. Command line build passes? __Y__
4. Changes have been smoke-tested? __Y__

**Comment by VWoeltjen** [comment]
Changes look good. I think there's a degree of commonality between AddAction and CreateAction that violates DRY. The basic flow I see:

* Create:
  1. Instantiate new object
  2. Enter Edit mode for new object
  3. Populate object properties using dialog (allowing Locator)
  4. Add to a destination's composition
* Add:
  1. Instantiate new object
  2. Populate object properties using dialog (disallowing Locator)
  3. Add to a destination's composition

Seems like these could share a parent class, or use a shared service to complete the last two steps, or something along those lines.

Reassigning to @akhenry - Thoughts? In the interest of getting this functionality in, I'd certainly be okay with deferring this for a follow up. Including checklist - go ahead and merge if you prefer to take that approach (or if I'm just wrong about the degree of commonality here.)

### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Comment by akhenry** [comment]
@VWoeltjen There is some commonality between CreateAction and AddAction, and it's probably enough to justify some sharing of code. There is also commonality between AddAction and SaveAction, and I'm wondering whether it would make sense to do the refactoring in the context of that ticket.

I'd like to merge this now because in its current state it represents a regression, and revisit this as part of #630 which I will prioritize this week. I'll create a new issue and link to #630

**Comment by VWoeltjen** [comment]
@akhenry Think that completely makes sense. I've added a note there and will complete this merge.

**Pull request merged**
