### PR TITLE
[Entanglement] Add "Set Primary Location" action

### PR DESCRIPTION
**Pull request by VWoeltjen**
Addresses #346

### Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? Y
3. Command line build passes? Y
4. Expect to pass code review? Y

### CODE REVIEW

**Comment by akhenry** [comment]
Code change looks fine. 

I'm not convinced that a user is going to know what this action does, or when it should be used, but I can't think of a good alternative right now :) It's creating an action to fix an implementation detail (ie. that 'location' hasn't been set). As far as the user is concerned it's already located properly within the tree, because it appears as the child of another object. 

Will it be obvious when this should be used? Maybe we need a visual indicator on objects (an exclamation mark or something) when there is something wrong with them (eg. 'location' is missing). Click on it (or launching a 'fix errors' action) would show a dialog offering corrective actions (such as "set primary location").

**Comment by VWoeltjen** [comment]
> I'm not convinced that a user is going to know what this action does, or when it should be used, but I can't think of a good alternative right now :) It's creating an action to fix an implementation detail (ie. that 'location' hasn't been set). As far as the user is concerned it's already located properly within the tree, because it appears as the child of another object. 

Agreed - I believe that during sprint planning we discussed this as a developer-facing tool to aid in migrations.

In the case of WARP, I have migration script that sets locations when the primary location is unambiguous (only one other object has that ID in its composition); it also provides a listing of all objects which need to be hand-fixed with this action. I've filed WTD-1593 in JIRA for this task (it is blocked by other deployment tasks currently)

Nominally, a user should never see this action available to them

**Comment by akhenry** [comment]
> Nominally, a user should never see this action available to them

Ok, fair enough. If it's not supposed to be a user-facing feature then it should be ok as it currently stands.

### Reviewer Checklist

* Changes appear to address issue? __Y__
* Appropriate unit tests included? __Y__
* Code style and in-line documentation are appropriate? __Y__
* Commit messages meet standards? __Y__

**Comment by akhenry** [comment]
Actually after I merged this is occurred to me that because it's a developer only tool it should probably be in a separated bundle and not included by default...

**Pull request merged**
