### PR TITLE
[Framework] Bump angular to 1.4.4

### PR DESCRIPTION
**Pull request by larkin**
Upgrade angular to latest version, also update angular-route.

Needs full testing to discover potential issues with angular 1.4.4; I will be reporting bugs I find in this pull request and resolving them here.

### CODE REVIEW

**Comment by larkin** [comment]
InfoService throws errors which results in multiple infobubbles displaying:

screen shot 2015-08-24 at 12 42 40 pm

screen shot 2015-08-24 at 12 39 28 pm

**Comment by VWoeltjen** [comment]
It seems that `mouseenter` listeners associated with the InfoGesture are being attached three times. In Angular 1.4.4, this is interpreted as "invoke this method three times on mouse enter", which is causing extra bubbles to be launched. Only the topmost one gets correctly removed (or cancelled, if not already showing) when the mouse leaves.

Added a quick-fix to this branch which avoids rescheduling the display of a bubble if one is already scheduled; still investigating why that listener is getting attached three times in the first place.

**Comment by VWoeltjen** [comment]
It appears that the root cause of the info bubble strangeness above is an Angular bug around attaching/detaching/reattching event listeners to `mouseenter` and `mouseleave` specifically. Filed angular/angular.js#12795

The multiple attachments of the same listener is weird (I think this is redundant attachment of gestures as multiple watches are fired for a given mct-representation), but should still be correct, because the extra gestures being attached are also being destroyed appropriately.

Fortunately, InfoGesture is the only place where `mouseenter` or `mouseleave` are listened-for in this fashion, so the workaround should be sufficient

**Comment by larkin** [comment]
@VWoeltjen stellar bugtracing here.  Always great to know it's not our bug and to be able to workaround it.

Anything else you've noticed in testing this branch that would prevent a merge?

**Comment by VWoeltjen** [comment]
Still looking through. My approach is to look through bundles and test the major functionality associated with each bundle. Will add notes here as I go; I'll add an author checklist once I think this is ready to merge

**Comment by VWoeltjen** [comment]
Now hitting an infinite digest exception when I try to create a Telemetry Panel while another Telemetry Panel is selected in the tree. I haven't observed this while creating other types; I'm speculating that this is related to some interaction between the Locator (probably LocatorController) and containment policies.

**Comment by VWoeltjen** [comment]
Believe I've tracked down all the regressions introduced by transitioning to 1.4.4. Method of verification was to look through platform bundles and smoke-test major functionality associated with each bundle.

A summary of changes:

* The `locator` control (e.g. to pick a destination for a telemetry panel) was causing an infinite digest when a Create action was invoked anywhere deeper than My Items. Not sure of the exact root cause, guessing the default depth for infinite-digest checking was reduced or something similar. In any event, stuck the `LocatorController` logic that exposes the top-level object (for the template to load a tree) into a timeout, to break up the digest cycles. Consequence of this is a (usually imperceptible) wait spinner appearing before the tree appears.
* Added a check to `RemoveAction` to avoid an exception that was being thrown while checking to see if the removal of the object should also trigger a navigation change. This exception also gets hit on the current `master` branch but Angular 1.2.23 seems to have swallow it (had to add a try-catch to observe it)
* Added a workaround for the redundant `mouseenter` calls associated with the `info` gesture.

Think this is ready to merge, pending second-party review. I wouldn't discourage any additional testing before merge, given the scope of the change :grin:

### Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? Y
3. Command line build passes? Y
4. Expect to pass code review? Y

**Comment by larkin** [comment]
Review Checklist
Changes appear to address issue? Y
Appropriate unit tests included? Y
Code style and in-line documentation are appropriate? Y
Commit messages meet standards? Y
Project-specific information isolated to appropriate branches? Y

Integration Checklist
Automated build passing after merge? Y
No merge conflicts (or resolution trivial/obvious)? Y
All master branches up-to-date after merge? Y
Project-specific information isolated to appropriate branches? Y

**Pull request merged**
