### PR TITLE
Review and integrate open639

### PR DESCRIPTION
**Pull request by charlesh88**
#639 started life as a humble Firefox bug. However, having determined that the issue revolved around media queries and (in this particular) the usage of a webkit-only query to determine if the user was in desktop mode or not, it seemed advantageous to take advantage of the new "Victorizr" code that places CSS classes in the body tag that determine the type of device in use. To that end, a significant refactoring of the CSS took place to remove usage of media queries that addresses a number of problems:

- #169  
- #639
- #683

I also took advantage of being in the CSS to hit a couple important but trivial style changes as well:

- #494
- #690 
- #335 
- #687

Because the refactoring of the media queries in particular touches a lot of elements, I took the time to unit test and verify each change in a pretty granular fashion; you can see this table in https://github.com/nasa/openmctweb/issues/639#issuecomment-185892209.

### Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? N, N/A
3. Command line build passes? Y
4. Changes have been smoke-tested? Y, see #639

### CODE REVIEW

**Comment by charlesh88** [comment]
@VWoeltjen Victor, do you want me to resolve conflicts in the branch and resubmit? Did not see that when I initially filed this.

**Comment by VWoeltjen** [comment]
Guessing conflicts are due to removal of built CSS files from repo in #693; if so, should be easy to resolve and I will do so before merging. If conflicts are more complicated than that, I'll reassign.

**Comment by VWoeltjen** [comment]
Tried to address merge conflicts. As expected, on a `git merge master` I see conflicts on the built CSS files that have been removed; this is easily resolved with `git rm **/theme-*.css`. But there are additional merge conflicts on some .scss files that involve actual divergent changes; not immediately obvious to me what to keep and what not to keep, so reassigning to @charlesh88 to resolve conflicts

**Comment by larkin** [comment]
Took care of merge conflicts, going to complete and integrate.

# Reviewer Checklist

Changes appear to address issue? Y 
Appropriate unit tests included? N/A (style changes)
Code style and in-line documentation are appropriate? Y
Commit messages meet standards? Y

**Pull request merged**
