### PR TITLE
[Examples] Rems data integration

### PR DESCRIPTION
**Pull request by akhenry**
Opening up for comments. A couple of things that need to happen for this to be enabled by default in the demo version

1. It currently uses JSON data from a remote source that will fail due to it being a cross origin request. Has been written to fallback to local data file if this happens, so it will still work, but it's not an ideal situation. Example will work with security disabled in Chrome, but can't recommend that people do this. There are four options here

    1. Add a requirement that the example must be run with a local proxy in place. Could add basic CORS proxy to app.js. Various reasons not to pursue this, but chief among them is that it adds a dependency to app.js.
    2. There is an open source API at http://marsweather.ingenology.com/ that provides the same data, but is more queryable. Unfortunately it provides paged results, which is no good for plotting. Evidence suggests that it does not set the necessary CORS response headers either. It is an open source project however (hosted on github), and is actually supported by NASA (I have the relevant NASA contact). It could be trivial to either effect the change ourselves, or ask for these changes to be made.
    3. We continue to use a local file as it currently does in fallback mode, but we update the fallback file  automatically as part of the build process, through CircleCI or a github hook or something.
    4. We just leave it as it is. It is intended as an example of historical data, so it only shows historical data.

2. If enabled by default, I think the time conductor needs to be defaulted to some time range that shows includes more REMS data. Ideally a range of several months

### CODE REVIEW

**Comment by larkin** [comment]
I think adding a local proxy to app.js is good enough for now and doesn't require too many changes and could be removed later.

**Comment by akhenry** [comment]
Ok, so I'm going to add a basic proxy, with fallback to static file if unsuccessful. This will allow people who are not using app.js to see something at least.

**Comment by akhenry** [comment]
Summary of changes:
- Added a new telemetry source that integrates with public REMS telemetry data
- Added a proxy service to app.js to bypass cross origin request restrictions

Going forward I would like to remove the restriction on using a local proxy (or disabling web security). There's a possible path for this using a different data source (http://marsweather.ingenology.com/), however this data source currently imposes paging, which would need to be addressed.

### Author Checklist

1. Changes address original issue? __Y__
2. Unit tests included and/or updated with changes? __N/A__ Did not include tests because example code
3. Command line build passes? __Y__
4. Changes have been smoke-tested? __Y__

**Comment by VWoeltjen** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/A (changes are in examples, out of scope for unit testing)
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Pull request merged**
